/ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng/bin/MismatchStat -i /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/bamprocess/SRR1107924.reorder.markdup.baseRecal.bam -x 1000000 -u -o /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/stat.txt;echo 1 complete
/ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng/bin/MutDet -i /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/bamprocess/SRR1107924.reorder.markdup.baseRecal.bam -r /ifs1/ST_SYSBIO/USER/liudb2/database/reference/hg19/hg19.fa -q 20 -v /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/stat.txt -u -o /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/binomFilter.txt.gz;echo 2 complete
perl /ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng/bin/filterMut.pl /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/binomFilter.txt.gz > /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/binomFilter.filt.fre.strand.txt;echo 3 complete
perl /ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng/bin/end.strand.mism.poly.rep.filt.pl --in /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/binomFilter.filt.fre.strand.txt --out /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/binomFilter.filt.fre.strand.end.simplerepeat.homopolymer.txt --simpleRepeat /ifs1/ST_SYSBIO/USER/liudb2/bin/TumorCare/database/repeat/hg19_simpleRepeat.reg.bed --reference /ifs1/ST_SYSBIO/USER/liudb2/database/reference/hg19/hg19.fa --endfre 0.9 --endp 0.05 --strandfre 0.9 --strandp 0.005 --homopolymer 5;echo 4 complete
perl /ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng/bin/pos_filter.pl --input /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/binomFilter.filt.fre.strand.end.simplerepeat.homopolymer.txt --loci /ifs1/ST_SYSBIO/USER/liudb2/database/GATK/2.8/hg19/dbsnp_138.hg19.vcf.gz --filt 2 --out /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/binomFilter.filt.fre.strand.end.simplerepeat.homopolymer.dbsnp.txt;echo 5 complete
perl /ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng/bin/pos_filter.pl --input /ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng/dbsnp/1000g.YH.Mongolian.dai.Dutch.snp.txt.gz --loci /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/binomFilter.filt.fre.strand.end.simplerepeat.homopolymer.dbsnp.txt --out /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/1000g.YH.Mongolian.dai.Dutch.exchange.txt;echo 6 complete
perl /ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng/bin/pos_filter.pl --input /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/binomFilter.filt.fre.strand.end.simplerepeat.homopolymer.dbsnp.txt -loci /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/1000g.YH.Mongolian.dai.Dutch.exchange.txt --filt 2 --out /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/binomFilter.filt.fre.strand.end.simplerepeat.homopolymer.dbsnp.snp.txt;echo complete 7
/ifs1/ST_SYSBIO/USER/liudb2/bin/TumorCare/bin/samtools index /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/bamprocess/SRR1107924.reorder.markdup.baseRecal.bam;echo complete 8
perl /ifs5/ST_COMG/USER/baiyali/RNA_editing/pan-cancer/SingleCel/human/hg19/4-parameter/Edit_detecting/bin/extract_reads_SE.pl /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/bamprocess/SRR1107924.reorder.markdup.baseRecal.bam /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/bwa/mutation.read.fq  /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_dete
ct/binomFilter.filt.fre.strand.end.simplerepeat.homopolymer.dbsnp.snp.txt /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/ed
iting_detect/readsvnum.txt;echo complete 9
/ifs1/ST_SYSBIO/USER/liudb2/bin/TumorCare/bin/bwa aln -o 1 -e 50 -m 100000 -l 32 -k 2 -t 4 -L -i 15 /ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng
/database/datanew/hg_mrna.fa /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/bwa/mutation.read.fq > /ifs5/ST_
COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/bwa/mutation.read.sai;echo complete 13
/ifs1/ST_SYSBIO/USER/liudb2/bin/TumorCare/bin/bwa samse /ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng/database/datanew/hg_mrna.fa /ifs5/ST_COMG/U
SER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/bwa/mutation.read.sai /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/d
ata_process/SRR1107924/new/editing_detect/bwa/mutation.read.fq  |/ifs1/ST_SYSBIO/USER/liudb2/bin/TumorCare/bin/samtools view -b -S -t /ifs1/ST_SYSBIO/USER/li
udb2/RNA_editing/bladder/xiongheng/database/datanew/hg_mrna.fa.fai - > /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editi
ng_detect/bwa/mutation.readS.bam;echo complete 14
perl /ifs5/ST_COMG/USER/baiyali/RNA_editing/pan-cancer/SingleCel/human/hg19/4-parameter/Edit_detecting/bin/bwa.fre.filt.SE.pl /ifs5/ST_COMG/USER/baiyali/RNA_
editing/Reprogramming/data_process/SRR1107924/new/editing_detect/bwa/mutation.readS.bam /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR
1107924/new/editing_detect/binomFilter.filt.fre.strand.end.simplerepeat.homopolymer.dbsnp.snp.txt /ifs1/ST_SYSBIO/USER/liudb2/database/annovar/humandb_hg19/h
g19_refGene.txt /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/readsvnum.txt /ifs5/ST_COMG/USER/baiyali/RNA_
editing/Reprogramming/data_process/SRR1107924/new/editing_detect/binomFilter.filt.fre.strand.end.simplerepeat.homopolymer.dbsnp.snp.bwa.txt;echo complete 15
/ifs1/ST_SYSBIO/USER/liudb2/bin/msort -k m1 -k n2 /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/binomFilter
.filt.fre.strand.end.simplerepeat.homopolymer.dbsnp.snp.bwa.txt > /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_de
tect/binomFilter.filt.fre.strand.end.simplerepeat.homopolymer.dbsnp.snp.bwa.sort.txt;echo complete 16
perl /ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng/pipeline/bin/annotation.new.pl /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_proce
ss/SRR1107924/new/editing_detect/binomFilter.filt.fre.strand.end.simplerepeat.homopolymer.dbsnp.snp.bwa.sort.txt /ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/blad
der/xiongheng/pipeline/database/alu/hg19.alu.bed /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/annotation.n
ew;echo complete 17
perl /ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng/bin/reads.support.pl /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107
924/new/editing_detect/annotation.new.anno.txt 2 /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/editing_detect/annotation.n
ew.anno.filt.txt;echo complete 18
perl /ifs5/ST_CANCERR_COMG/USER/qiusi/pipeline/RNA_editing/strand.anno.pl /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/ed
iting_detect/annotation.new.anno.filt.txt /ifs1/ST_SYSBIO/USER/liudb2/RNA_editing/bladder/xiongheng/pipeline/bin/lincRNA/hg19_refGene.txt /ifs1/ST_SYSBIO/USE
R/liudb2/RNA_editing/bladder/xiongheng/pipeline/database/alu/hg19.alu.bed /ifs5/ST_COMG/USER/baiyali/RNA_editing/Reprogramming/data_process/SRR1107924/new/ed
iting_detect/annotation.new.anno.filt.lincRNA.txt;echo complete 19
